version: '3.9'

services:
  fastseat.api:
    image: ${DOCKER_REGISTRY-}fastseatapi
    container_name: FastSeat.Api
    build:
      context: .
      dockerfile: src/API/FastSeat.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  fastseat.database:
    image: postgres:latest
    container_name: FastSeat.Database
    environment:
      - POSTGRES_DB=fastseat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastseat.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: FastSeat.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080

  fastseat.seq:
    image: datalust/seq:latest
    container_name: FastSeat.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  fastseat.redis:
    image: redis:latest
    container_name: FastSeat.Redis
    restart: always
    ports:
      - 6379:6379

  fastseat.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: FastSeat.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
